---
title-meta: iq-raw
execute:
  cache: true
---

```{r}
#| include: false

# <!-- <<PROMPT>> -->

# Summarize and interpret these neuropsychological test scores as if you are an
# experienced clinical neuropsychologist. For scores that are below average,
# give a brief example of how this could impact the patient's daily life and functioning. Organize your
# summary and interpretation from scores that are above average to below average to delineate
# relative strengths and weaknesses.

# <!-- <<START>> -->

```
 
A composite estimate of working memory^[(ref:working-memory)] and processing speed^[(ref:processing-speed)] (i.e., cognitive proficiency) was Exceptionally High and a relative strength|weakness. 
An estimate of working memory capacity^[(ref:working-memory)] fell in the Exceptionally High range and was and a relative strength|weakness. 
A composite screening measure of Ashish's visuoperceptual skills, attention to detail, and visuoconstructional skills fell in the Above Average classification range. 
An estimate of fluid intelligence (*G*f) was classified as High Average. 
Crystallized intelligence (*G*c) was classified as High Average and ranked at the 84th percentile. 
An estimate of premorbid verbal ability level fell within the High Average range.^[(ref:premorbid)] 
An overall screening measure of the examinee's attentional functioning was High Average. 
Finally, a comprehensive measure of neuropsychological functioning (independent of general intelligence) in the domains of attentional and executive functioning, language, spatial processing, and memory fell in the High Average range. 
A composite measure of executive skills involving planning, inhibition, speed/fluency, and generativity fell in the Average range. 
A composite screening measure of language comprehension and word-finding abilities fell in the Average classification range. 
Collective performance across measures of processing speed and cognitive efficiency^[(ref:processing-speed)] was Average and a relative strength|weakness. 
A composite measure of the examinee's verbal and visual memory functioning was Average.
